apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-eureka-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: eureka
  replicas: 1
  template: 
    metadata:
      labels:
        app: cloud
        component: eureka
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_HOST
          value: configserver-service
        name: eureka
        image: marcopaga/cloud-eureka
        ports:
        - containerPort: 8761
        readinessProbe:
          httpGet:
            path: /health
            port: 8761
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8761
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: cloud
spec:
  type: LoadBalancer
  selector:
    app: cloud
    component: eureka
  ports:
  - port: 8761
    targetPort: 8761
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-configserver-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: configserver
  replicas: 1
  template: 
    metadata:
      labels:
        app: cloud
        component: configserver
    spec:
      containers:
      - env:
        - name: EUREKA_HOST
          value: eureka-service
        - name: CONFIGSERVER_HOST
          value: configserver-service
        name: configserver
        image: marcopaga/cloud-configserver
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  labels:
    app: cloud
spec:
  type: LoadBalancer
  selector:
    app: cloud
    component: configserver
  ports:
  - port: 8888
    targetPort: 8888
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-edgeservice-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: edgeservice
  replicas: 1
  template: 
    metadata:
      labels:
        app: cloud
        component: edgeservice
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_HOST
          value: configserver-service
        - name: EUREKA_HOST
          value: eureka-service #eureka-service.default.svc.cluster.local
        name: edgeservice
        image: marcopaga/cloud-edgeservice
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: edgeservice-service
  labels:
    app: cloud
spec:
  type: LoadBalancer
  selector:
    app: cloud
    component: edgeservice
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-frontend-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: frontend
  replicas: 1
  template: 
    metadata:
      labels:
        app: cloud
        component: frontend
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_HOST
          value: configserver-service
        - name: EUREKA_HOST
          value: eureka-service #eureka-service.default.svc.cluster.local
        - name: ZIPKIN_HOST
          value: zipkin-service
        name: frontend
        image: marcopaga/cloud-frontend
        ports:
        - containerPort: 8091
        readinessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-backend-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: backend
  replicas: 2
  template: 
    metadata:
      labels:
        app: cloud
        component: backend
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_HOST
          value: configserver-service
        - name: EUREKA_HOST
          value: eureka-service #eureka-service.default.svc.cluster.local
        - name: ZIPKIN_HOST
          value: zipkin-service
        name: backend
        image: marcopaga/cloud-backend
        ports:
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 10

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-zipkin-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud
        component: zipkin
    spec:
      containers:
      - env:
        - name: EUREKA_HOST
          value: eureka-service #eureka-service.default.svc.cluster.local
        name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: cloud
spec:
  type: LoadBalancer
  selector:
    app: cloud
    component: zipkin
  ports:
  - port: 9411
    targetPort: 9411
