version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - JAVA_OPTS="-Xms256m -Xmx512m"
  configserver:
    build: configserver/.
    image: marcopaga/cloud-configserver
    ports:
      - "8888:8888"
  eureka:
    build: eureka/.
    image: marcopaga/cloud-eureka
    ports:
      - "8761:8761"
    environment:
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - configserver
  edgeservice:
    build: edgeservice/.
    image: marcopaga/cloud-edgeservice
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=eureka
      - ZIPKIN_HOST=zipkin
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - eureka
  frontend:
    build: frontend/.
    image: marcopaga/cloud-frontend
    ports:
      - "8091:8091"
    environment:
      - EUREKA_HOST=eureka
      - ZIPKIN_HOST=zipkin
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - eureka
      - zipkin
  backend:
    build: backend/.
    image: marcopaga/cloud-backend
    ports:
      - "8090:8090"
    environment:
      - EUREKA_HOST=eureka
      - ZIPKIN_HOST=zipkin
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - eureka
      - zipkin