{{- if .Values.zipkin.enabled -}}
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "cloud.fullname" $ }}-zipkin-deployment
  labels:
    component: zipkin
    app: {{ template "cloud.name" . }}
    chart: {{ template "cloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: zipkin
      app: {{ template "cloud.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        component: zipkin
        app: {{ template "cloud.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: EUREKA_HOST
          value: eureka-service
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx768m"
        name: zipkin
        image: "{{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}"
        imagePullPolicy: {{ $.Values.zipkin.image.pullPolicy }}
        ports:
        - containerPort: 9411
        resources:
          limits:
            memory: "1G"
            cpu: "0.5"
{{- end }}